require 'rubygems'
require 'isolate'

Isolate.now! do
  gem 'erubis'
end

require 'erubis'

module Helpers
  def sheet_tab(name, id, checked=false)
    <<-END
<input type="radio" name="attr_tab" class="sheet-tab sheet-tab#{id}" value="#{id}" title="#{name}"#{' checked="checked"' if checked}/>
<span class="sheet-tab sheet-tab#{id}">#{name}</span>
END
  end
end

class Page
  include Helpers

  def initialize(filename)
    @filename = filename
  end

  def write(outfile)
    File.open(outfile, 'w') do |file|
      file.puts(build)
    end
  end

private
  def build
    erb.result(binding)
  end

  def erb
    Erubis::Eruby.new(template)
  end

  def template
    File.read(@filename)
  end
end

task :default do
  Page.new('pathfinder-neceros.html.erb').write('pathfinder-neceros.html')
end
